# Generated by Django 3.0.8 on 2020-11-02 07:13

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Type of the game')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('status', django_fsm.FSMField(default='disable', max_length=50)),
            ],
        ),
    ]
