version: '3.4'

# ################################################################################
# extension field to re-use configuration fragments
# ################################################################################

x-server_base: &server_base
    build:
        context: ./
        dockerfile: ./server/Dockerfile
    volumes:
        - ./server:/server
    env_file:
      - .env

services:

  # ################################################################################
  # Django Backend / API / Daphne ASGI
  # ################################################################################
    daphne_asgi:
        <<: *server_base
        command: daphne -b 0.0.0.0 -p 8001 config.asgi:application
        depends_on:
            - redis

  # ################################################################################
  # Django Backend / API / Gunicorn WSGI
  # ################################################################################
    gunicorn:
        <<: *server_base
        command: gunicorn config.wsgi -c ./config/gunicorn.py --access-logfile '-'
        depends_on:
            - daphne_asgi

  # ################################################################################
  # Celery scheduler
  # ################################################################################
    celery_beat:
        <<: *server_base
        command: celery beat --app config.celery:app -l info
        depends_on:
            - redis
            - daphne_asgi
            - celery

  # ################################################################################
  # Celery worker running async tasks
  # ################################################################################
    celery:
        <<: *server_base
        command: celery worker --app config.celery:app --loglevel=info --logfile=logs/celery.log
        depends_on:
            - redis
            - daphne_asgi

  # ################################################################################
  # Queue broker for Celery
  # ################################################################################
    redis:
        image: redis:6.0.6-alpine

  # ################################################################################
  # Workers health monitoring
  # ################################################################################
    dashboard:
        <<: *server_base
        command:  flower -A config.celery:app --port=5555 --broker=redis://redis:6379/0
        ports:
            - 5555:5555
        depends_on:
            - daphne_asgi
            - redis
            - celery

  # ################################################################################
  # Nginx
  # ################################################################################
    nginx:
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        depends_on:
            - daphne_asgi
        ports:
            - 80:80